name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "n43635.top"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.n43635.top", custom_domain = true },
#  { pattern = "quay.n43635.top", custom_domain = true },
#  { pattern = "gcr.n43635.top", custom_domain = true },
#  { pattern = "k8s-gcr.n43635.top", custom_domain = true },
#  { pattern = "k8s.n43635.top", custom_domain = true },
#  { pattern = "ghcr.n43635.top", custom_domain = true },
#  { pattern = "cloudsmith.n43635.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.n43635.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
